// auth
export const CREATE_REQUEST_TOKEN = 'CREATE_REQUEST_TOKEN';
export const VALIDATE_RES_TOKEN = 'VALIDATE_RES_TOKEN';
export const VALIDATE_ERROR = 'VALIDATE_ERROR';
export const SESSION_ID = 'SESSION_ID';
export const CURRENT_USER = 'CURRENT_USER';
export const LOGOUT = 'LOGOUT';
